# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-22 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_of_birth',
            field=models.DateField(default='null', max_length=8),
            preserve_default=False,
        ),
    ]
