# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-22 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_users_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='date_of_birth',
        ),
    ]
