# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-22 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_users_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_of_birth',
            field=models.DateField(verbose_name='YYYY-MM-DD'),
        ),
    ]
